
title: Purushottam Mohanty

email: purushottam.mohanty@gmail.com

#remote_theme: "mmistakes/minimal-mistakes@4.21.0"
theme: minimal-mistakes-jekyll

# Build settings
markdown: kramdown
#remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" #"default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "Purushottam Mohanty"

include:
  - _pages