
title: Purushottam Mohanty
url: "https://purushottammohanty.github.io"


#remote_theme: "mmistakes/minimal-mistakes@4.21.0"
#theme: minimal-mistakes-jekyll

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "default" #"default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


# Plugins (previously gems:)
plugins:
  - jekyll-include-cache


author:
  name   : "Purushottam Mohanty"
  avatar : "/assets/images/profile_pic.jpeg"
  bio    :
    Data Associate, Good Business Lab

include: 
  - _pages

