project:
  type: website
  output-dir: docs

# Meta
description-meta: "Quarto Academic Website Template adapted by Dr. Gang He"
author-meta: "Dr. Gang He"

website:
  title: "Home"
  image: "https://quarto.org/quarto.png"
 
  navbar:
    background: light

    left:
      - text: Research
      - text: Datasets
      - text: Blog
        href: posts.qmd
      - text: CV

    right: 
      - icon: github
        href: https://github.com/purushottammohanty/purushottammohanty.github.io
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Purushottam Mohanty](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    #center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://purushottammohanty.github.io
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://purushottammohanty.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://purushottammohanty.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

