---
title: 'Applying for J1 Visa in India'
excerpt: 'I am sharing my J1 visa application experience.'
author: "Purushottam Mohanty"
date: "06/02/2022"
output:
  html_document:
    theme: lumen
    highlight: pygments
---

The visa application process can be confusing especially for fresh applicants from India. I'm writing the following blog to share my experience. I hope it is helpful for future applicants. Note that, I was applying for a J1 Research Scholar visa for a fully funded position at University of Chicago. You're case might be different so please be careful while referring to this blog.

## Step 1: Receiving the DS-2019 Form
Congratulations! You have received an offer from an university/organisation who is willing to sponsor you as a research scholar. The organisation will physically mail you a document referred to as DS-2019 which contains all the relevant details of the program. This document is generated when the international office of the university fills in all the relevant program information in the Student and Exchange Visitor Information System (SEVIS). The document includes your SEVIS ID, official program start and end date, sponsor name, program number, financial funding along with several other details.         
    
Note: Please verify all the details written on the document and check for any mistakes or spelling errors. If you spot any mistakes or have any questions reach out to the international office of your university and get it clarified.  

## Step 2: Pay SEVIS Fee
The next step involves paying the mandatory SEVIS fee. You can do so at https://www.fmjfee.com/i901fee/index.html As a J1 research scholar the fee is 220$. This payment confirmation is also called as I-901 Fee as well.

